routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('auth:web')->group(function () {
    Route::view('/', 'admin.dashboard.index')->name('dashboard.index');
    Route::resource('users', 'UsersController');
    Route::resource('home-banners', 'HomeBannersController');
    Route::resource('pages', 'PagesController');
    Route::resource('services', 'ServicesController');
    Route::resource('categories', 'CategoriesController');
    Route::resource('image-uploader', 'ImageUploaderController')->only(['store', 'destroy']);
    Route::resource('offers', 'OffersController');
    Route::resource('events', 'EventsController');
    Route::get('events/{id}/show-in-home', 'EventsController@showInHome')->name('events.show-in-home');
    Route::get('offers/{id}/show-in-home', 'OffersController@showInHome')->name('offers.show-in-home');
    Route::resource('programs', 'ProgramsController');
    Route::get('programs/{id}/show-in-home', 'ProgramsController@showInHome')->name('programs.show-in-home');
    Route::resource('certificates', 'CertificatesController');
    Route::resource('dubai-services', 'DubaiServicesController');
    Route::resource('partners', 'PartnersController');
    Route::resource('newsletters', 'NewslettersController');
    Route::resource('contacts', 'ContactsController');
    Route::resource('hajj-programs', 'HajjProgramsController');
    Route::resource('omra-programs', 'OmraProgramsController');
    Route::resource('hajj-hotels', 'HajjHotelsController');
    Route::resource('omra-hotels', 'OmraHotelsController');
    Route::apiResource('photos', 'PhotosController');
    Route::view('gallery/photos', 'admin.gallery.photos')->name('gallery.photos');
    Route::resource('bookings', 'BookingsController');
    Route::get('settings', 'SettingsController@index')->name('settings.index');
    Route::get('settings/social', 'SettingsController@editSocialMedia')->name('settings.social');
    Route::post('settings/social', 'SettingsController@updateSocialMedia')->name('settings.update-social');
    Route::get('settings/pages-header', 'SettingsController@editPagesHeader')->name('settings.pages-header');
    Route::post('settings/pages-header', 'SettingsController@updatePagesHeader')->name('settings.update-pages-header');
});

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
*/
Route::namespace('Front')->prefix('{lang?}')->group(function () {
    Route::view('/', 'front.home');
    Route::get('pages/{slug}', 'PagesController@show');
    Route::resource('services', 'ServicesController')->only(['index', 'show']);
    Route::resource('dubai-services', 'DubaiServicesController')->only(['index', 'show']);
    Route::resource('offers', 'OffersController')->only(['index', 'show']);
    Route::get('our-programs', 'ProgramsController@categories');
    Route::get('our-programs/{category_slug}/programs', 'ProgramsController@index');
    Route::get('our-programs/{program_slug}', 'ProgramsController@show');
    Route::resource('certificates', 'CertificatesController')->only(['index']);
    Route::get('contact-us', 'ContactsController@show');
    Route::post('contacts/send', 'ContactsController@send');
    Route::get('jobs', 'JobsController@show');
    Route::post('jobs/send', 'JobsController@send');
    Route::resource('hajj-programs', 'HajjProgramsController')->only(['index', 'show']);
    Route::resource('umra-programs', 'OmraProgramsController')->only(['index', 'show']);
    Route::resource('hajj-hotels', 'HajjHotelsController')->only(['index', 'show']);
    Route::resource('umra-hotels', 'OmraHotelsController')->only(['index', 'show']);
    Route::view('gallery/photos', 'front.gallery.photos');
    Route::resource('newsletters', 'NewslettersController')->only(['index', 'show']);

    Route::resource('events', 'EventsController')->only(['index', 'show']);

    Route::middleware('auth:web')->group(function(){
        Route::get('programs/{slug}/book', 'BookingsController@create')->name('bookings.create');
        Route::post('programs/{slug}/book', 'BookingsController@store')->name('bookings.store');
        Route::get('programs/{slug}/book/response', 'BookingsController@response')->name('bookings.response');
    });
});

app/Http/Controllers/Admin/HajjHotelsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Hotel;
use App\Http\Traits\ImageTrait;

class HajjHotelsController extends Controller
{
    use ImageTrait;

    public function index(Request $request){
        $query = Hotel::where('section', 'hajj');

        if($request->filled('key')){
            $query->where('title_en', 'like', "%{$request->key}%")
                ->orWhere('title_ar', 'like', "%{$request->key}%" );
        }

        $hotels = $query->paginate(config('system.limit_per_page'));
        return view('admin.hajj-hotels.index')->with('hotels', $hotels);
    }

    public function create(){
        return view('admin.hajj-hotels.create');
    }

    public function store(Request $request){

        $this->validate($request, [
            'image'=>'required|image|max:2000',
            'title_en'=>'required',
            'title_ar'=>'required',
            'body_en'=>'required',
            'body_ar'=>'required',
        ]);

        $inputs = $request->except(['image']);
        $inputs['section'] = 'hajj';
        //upload image
        if($request->hasFile('image')){
            if ($request->file('image')->isValid()) {
                $inputs['image'] = $this->uploadImageAndFit($request->image, 'hotels', 100);
            }
        }

        $hotel = Hotel::create($inputs);
        flash()->success('data saved successfully');
        return \redirect()->route('admin.hajj-hotels.index');
    }

    public function edit($id){
        $hotel = Hotel::findOrFail($id);
        return view('admin.hajj-hotels.edit')->with('hotel', $hotel);
    }

    public function update(Request $request, $id){
        $this->validate($request, [
            'image'=>'nullable|image|max:2000'
        ]);

        $inputs = $request->except(['image']);

        $hotel = Hotel::findOrFail($id);

        //upload image
        if($request->hasFile('image')){
            $this->deleteImage('hotels', $hotel->getOriginal('image'));
            $inputs['image'] = $this->uploadImageAndFit($request->image, 'hotels', 100);
        }

        $hotel->update($inputs);
        flash()->success('data saved successfully');
        return \redirect()->route('admin.hajj-hotels.index');
    }

    public function destroy($id){
        $hotel = Hotel::findOrFail($id);
        $this->deleteImage('hotels', $hotel->getOriginal('image'));
        $hotel->delete();
        flash()->success('data deleted successfully');
        return redirect()->back();
    }
}

app/Http/Controllers/Front/HajjHotelsController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Hotel;

class HajjHotelsController extends Controller
{
    public function index(){
        $hotels = Hotel::where('section', 'hajj')->paginate(10);
        return view('front.hajj-hotels.index')->with('hotels', $hotels);
    }

    public function show($slug){
        $hotel = Hotel::whereSlug($slug)->first();
        if(!$hotel){
            abort(404);
        }
        return view('front.hajj-hotels.show')->with('hotel', $hotel);
    }
}

resources/views/admin/hajj-hotels/create.blade.php
@extends('admin.layouts.master')
@section('breadcrumb') @breadcrumb([ 'title'=>'Hajj Hotels', 'crumbs'=>[ ['title'=>'Hajj Hotels', 'url'=>route('admin.hajj-hotels.index')], ['title'=>'Create', 'url'=>''] ] ])
@endsection

@section('content')
{{-- content block --}}
<form action="{{route('admin.hajj-hotels.store')}}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        {{-- data in english --}}
        <div class="col-6">
            <div class="card">
                <div class="card-header">Data in English</div>
                <div class="card-body">
                    @input(['name'=>'title_en', 'label'=>'Name'])
                    @textarea(['name'=>'description_en', 'label'=>'Description'])
                    @textarea(['name'=>'body_en', 'label'=>'Details', 'class'=>'ckeditor'])
                    @input(['type'=>'file', 'name'=>'image', 'label'=>'Image'])
                </div>
            </div>
        </div>
        {{-- data in arabic --}}
        <div class="col-6">
            <div class="card">
                <div class="card-header">Data in Arabic</div>
                <div class="card-body">
                        @input(['name'=>'title_ar', 'label'=>'Name'])
                        @textarea(['name'=>'description_ar', 'label'=>'Description'])
                        @textarea(['name'=>'body_ar', 'label'=>'Details', 'class'=>'ckeditor'])
                </div>
            </div>
        </div>
    </div>

    {{-- buttons --}}
    <div class="card">
            <div class="card-body">@button(['title'=>'Save', 'icon'=>'floppy-o'])</div>
    </div>


@endsection

resources/views/admin/hajj-hotels/edit.blade.php
@extends('admin.layouts.master')
@section('breadcrumb') @breadcrumb([ 'title'=>'Hajj Hotels', 'crumbs'=>[ ['title'=>'Hajj Hotels', 'url'=>route('admin.hajj-hotels.index')],
['title'=>'Edit', 'url'=>''] ] ])
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <a href="#" class="btn btn-default" data-toggle="modal" data-target="#hotel-images"><i class="fa fa-picture-o"></i> Hotel Gallery</a>
    </div>

    </div>
</div>

    {{-- content block --}}
    <form action="{{route('admin.hajj-hotels.update', $hotel->id)}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="row">
                {{-- data in english --}}
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">Data in English</div>
                        <div class="card-body">
                            @input(['name'=>'title_en', 'label'=>'Name', 'value'=>$hotel->title_en])
                            @textarea(['name'=>'description_en', 'label'=>'Description', 'value'=>$hotel->description_en])
                            @textarea(['name'=>'body_en', 'label'=>'Details', 'value'=>$hotel->body_en, 'class'=>'ckeditor'])
                            @input(['type'=>'file', 'name'=>'image', 'label'=>'Image'])
                        </div>
                    </div>
                </div>
                {{-- data in arabic --}}
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">Data in Arabic</div>
                        <div class="card-body">
                                @input(['name'=>'title_ar', 'label'=>'Name', 'value'=>$hotel->title_ar])
                                @textarea(['name'=>'description_ar', 'label'=>'Description', 'value'=>$hotel->description_ar])
                                @textarea(['name'=>'body_ar', 'label'=>'Details', 'value'=>$hotel->body_ar, 'class'=>'ckeditor'])
                        </div>
                    </div>
                </div>
            </div>

        {{-- buttons --}}
        <div class="card">
                <div class="card-body">@button(['title'=>'Save', 'icon'=>'floppy-o'])</div>
        </div>
    </form>

    <!-- Hotel images modal -->
<div class="modal fade" id="hotel-images" tabindex="-1" role="dialog" aria-labelledby="hotel-imagesLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="hotel-imagesLabel">Hotel Images</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            @include('admin.includes.photos', ['k'=>'hotel_id', 'v'=>$hotel->id])
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/admin/hajj-hotels/index.blade.php
@extends('admin.layouts.master')
@section('breadcrumb') @breadcrumb([ 'title'=>'Hajj Hotels', 'crumbs'=>[ ['title'=>'Hajj Hotels', 'url'=>'']
] ])
@endsection

@section('content')

    {{-- search block --}}
    {{-- search block --}}
    <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-10">
                        <form class="form-inline" method="GET">
                            <input name="key" type="text" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" placeholder="key.." value="{{request('key', '')}}">
                            <button type="submit" class="btn btn-primary mb-2"><i class="fa fa-search"></i> Search</button>
                        </form>
                    </div>
                    <div class="col-2 text-right">
                        <a href="{{route('admin.hajj-hotels.create')}}" class="btn btn-default"><i class="fa fa-plus-circle"></i> Add new</a>
                    </div>
                </div>

            </div>
        </div>

    {{-- content block --}}
    <div class="card">
    <div class="card-body">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Image</th>
                    <th scope="col">Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($hotels as $hotel)
                <tr>
                    <th scope="row">{{$hotel->id}}</th>
                    <td>@thumb(['image'=>$hotel->image, 'title'=>$hotel->title_en])</td>
                    <td>{{$hotel->title_en}}</td>
                    <td class="text-right">
                        @actionLink(['url'=>route('admin.hajj-hotels.edit', $hotel->id), 'icon'=>'fa-pencil-square-o fa-2x', 'tooltip'=>'Edit'])
                        @deleteLink(['url'=>route('admin.hajj-hotels.destroy', $hotel->id), 'icon'=>'trash fa-2x', 'tooltip'=>'Delete', 'confirm'=>'Are you sure to delete?'])
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <div class="text-right">
                {{ $hotels->links() }}
            </div>

    </div>
</div>
@endsection