routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('auth:web')->group(function () {
    Route::view('/', 'admin.dashboard.index')->name('dashboard.index');
    Route::resource('users', 'UsersController');
    Route::resource('home-banners', 'HomeBannersController');
    Route::resource('pages', 'PagesController');
    Route::resource('services', 'ServicesController');
    Route::resource('categories', 'CategoriesController');
    Route::resource('image-uploader', 'ImageUploaderController')->only(['store', 'destroy']);
    Route::resource('offers', 'OffersController');
    Route::resource('events', 'EventsController');
    Route::get('events/{id}/show-in-home', 'EventsController@showInHome')->name('events.show-in-home');
    Route::get('offers/{id}/show-in-home', 'OffersController@showInHome')->name('offers.show-in-home');
    Route::resource('programs', 'ProgramsController');
    Route::get('programs/{id}/show-in-home', 'ProgramsController@showInHome')->name('programs.show-in-home');
    Route::resource('certificates', 'CertificatesController');
    Route::resource('dubai-services', 'DubaiServicesController');
    Route::resource('partners', 'PartnersController');
    Route::resource('newsletters', 'NewslettersController');
    Route::resource('contacts', 'ContactsController');
    Route::resource('hajj-programs', 'HajjProgramsController');
    Route::resource('omra-programs', 'OmraProgramsController');
    Route::resource('hajj-hotels', 'HajjHotelsController');
    Route::resource('omra-hotels', 'OmraHotelsController');
    Route::apiResource('photos', 'PhotosController');
    Route::view('gallery/photos', 'admin.gallery.photos')->name('gallery.photos');
    Route::resource('bookings', 'BookingsController');
    Route::get('settings', 'SettingsController@index')->name('settings.index');
    Route::get('settings/social', 'SettingsController@editSocialMedia')->name('settings.social');
    Route::post('settings/social', 'SettingsController@updateSocialMedia')->name('settings.update-social');
    Route::get('settings/pages-header', 'SettingsController@editPagesHeader')->name('settings.pages-header');
    Route::post('settings/pages-header', 'SettingsController@updatePagesHeader')->name('settings.update-pages-header');
});

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
*/
Route::namespace('Front')->prefix('{lang?}')->group(function () {
    Route::view('/', 'front.home');
    Route::get('pages/{slug}', 'PagesController@show');
    Route::resource('services', 'ServicesController')->only(['index', 'show']);
    Route::resource('dubai-services', 'DubaiServicesController')->only(['index', 'show']);
    Route::resource('offers', 'OffersController')->only(['index', 'show']);
    Route::get('our-programs', 'ProgramsController@categories');
    Route::get('our-programs/{category_slug}/programs', 'ProgramsController@index');
    Route::get('our-programs/{program_slug}', 'ProgramsController@show');
    Route::resource('certificates', 'CertificatesController')->only(['index']);
    Route::get('contact-us', 'ContactsController@show');
    Route::post('contacts/send', 'ContactsController@send');
    Route::get('jobs', 'JobsController@show');
    Route::post('jobs/send', 'JobsController@send');
    Route::resource('hajj-programs', 'HajjProgramsController')->only(['index', 'show']);
    Route::resource('umra-programs', 'OmraProgramsController')->only(['index', 'show']);
    Route::resource('hajj-hotels', 'HajjHotelsController')->only(['index', 'show']);
    Route::resource('umra-hotels', 'OmraHotelsController')->only(['index', 'show']);
    Route::view('gallery/photos', 'front.gallery.photos');
    Route::resource('newsletters', 'NewslettersController')->only(['index', 'show']);

    Route::resource('events', 'EventsController')->only(['index', 'show']);

    Route::middleware('auth:web')->group(function(){
        Route::get('programs/{slug}/book', 'BookingsController@create')->name('bookings.create');
        Route::post('programs/{slug}/book', 'BookingsController@store')->name('bookings.store');
        Route::get('programs/{slug}/book/response', 'BookingsController@response')->name('bookings.response');
    });
});

app/DubaiService.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class DubaiService extends Model
{
    use Sluggable;

    protected $fillable = ['image', 'title_en', 'description_en', 'title_ar', 'description_ar', 'body_en', 'body_ar'];

    public $timestamps = false;

    public function getImageAttribute($value){
        if($value){
            return [
                'original'=>asset('storage/dubai-services/'.$value),
                'thumb'=>asset('storage/dubai-services/thumb/'.$value)
            ];
        }
        return $value;
    }

     /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title_en'
            ]
        ];
    }

}

app/Http/Controllers/Admin/DubaiServicesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DubaiService;
use App\Http\Traits\ImageTrait;

class DubaiServicesController extends Controller
{
    use ImageTrait;

    public function index(Request $request){
        $query = DubaiService::query();

        if($request->filled('key')){
            $query->where('title_en', 'like', "%{$request->key}%")
                ->orWhere('title_ar', 'like', "%{$request->key}%" );
        }

        $services = $query->paginate(config('system.limit_per_page'));
        return view('admin.dubai-services.index')->with('services', $services);
    }

    public function create(){
        return view('admin.dubai-services.create');
    }

    public function store(Request $request){

        $this->validate($request, [
            'image'=>'required|image|max:2000',
            'title_en'=>'required',
            'title_ar'=>'required',
            'body_en'=>'required',
            'body_ar'=>'required',
        ]);

        $inputs = $request->except(['image']);
        //upload image
        if($request->hasFile('image')){
            if ($request->file('image')->isValid()) {
                $inputs['image'] = $this->uploadImageAndFit($request->image, 'dubai-services', 370, 201);
            }
        }

        $service = DubaiService::create($inputs);
        flash()->success('data saved successfully');
        return redirect()->route('admin.dubai-services.index');
    }

    public function edit($id){
        $service = DubaiService::findOrFail($id);
        return view('admin.dubai-services.edit')->with('service', $service);
    }

    public function update(Request $request, $id){
        $this->validate($request, [
            'image'=>'nullable|image|max:2000'
        ]);

        $inputs = $request->except(['image']);

        $service = DubaiService::findOrFail($id);

        //upload image
        if($request->hasFile('image')){
            $this->deleteImage('services', $service->getOriginal('image'));
            $inputs['image'] = $this->uploadImageAndFit($request->image, 'dubai-services', 370, 201);
        }

        $service->update($inputs);
        flash()->success('data saved successfully');
        return \redirect()->route('admin.dubai-services.index');
    }

    public function destroy($id){
        $service = DubaiService::findOrFail($id);
        $this->deleteImage('dubai-services', $service->getOriginal('image'));
        $service->delete();
        flash()->success('data deleted successfully');
        return redirect()->back();
    }
}

app/Http/Controllers/Front/DubaiServicesController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DubaiService;

class DubaiServicesController extends Controller
{
    public function index(){
        $services = DubaiService::all();
        return view('front.dubai-services.index')->with('services', $services);
    }

    public function show($slug){
        $service = DubaiService::whereSlug($slug)->first();
        if(!$service){
            abort(404);
        }
        return view('front.dubai-services.show')->with('service', $service);
    }
}

resources/views/admin/dubai-services/create.blade.php
@extends('admin.layouts.master')
@section('breadcrumb') @breadcrumb([ 'title'=>'Dubai Services', 'crumbs'=>[ ['title'=>'Dubai Services', 'url'=>route('admin.dubai-services.index')], ['title'=>'Create', 'url'=>''] ] ])
@endsection

@section('content')
{{-- content block --}}
<form action="{{route('admin.dubai-services.store')}}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        {{-- data in english --}}
        <div class="col-6">
            <div class="card">
                <div class="card-header">Data in English</div>
                <div class="card-body">
                    @input(['name'=>'title_en', 'label'=>'Title'])
                    @textarea(['name'=>'description_en', 'label'=>'Description'])
                    @textarea(['name'=>'body_en', 'label'=>'Body', 'class'=>'ckeditor'])
                    @input(['type'=>'file', 'name'=>'image', 'label'=>'Image'])
                </div>
            </div>
        </div>
        {{-- data in arabic --}}
        <div class="col-6">
            <div class="card">
                <div class="card-header">Data in Arabic</div>
                <div class="card-body">
                        @input(['name'=>'title_ar', 'label'=>'Title'])
                        @textarea(['name'=>'description_ar', 'label'=>'Description'])
                        @textarea(['name'=>'body_ar', 'label'=>'Body', 'class'=>'ckeditor'])
                </div>
            </div>
        </div>
    </div>

    {{-- buttons --}}
    <div class="card">
            <div class="card-body">@button(['title'=>'Save', 'icon'=>'floppy-o'])</div>
    </div>


@endsection

resources/views/admin/dubai-services/edit.blade.php
@extends('admin.layouts.master')
@section('breadcrumb') @breadcrumb([ 'title'=>'Dubai Services', 'crumbs'=>[ ['title'=>'Dubai Services', 'url'=>route('admin.dubai-services.index')],
['title'=>'Edit', 'url'=>''] ] ])
@endsection

@section('content')

    {{-- content block --}}
    <form action="{{route('admin.dubai-services.update', $service->id)}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="row">
                {{-- data in english --}}
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">Data in English</div>
                        <div class="card-body">
                            @input(['name'=>'title_en', 'label'=>'Title', 'value'=>$service->title_en])
                            @textarea(['name'=>'description_en', 'label'=>'Description', 'value'=>$service->description_en])
                            @textarea(['name'=>'body_en', 'label'=>'Body', 'value'=>$service->body_en, 'class'=>'ckeditor'])
                            @input(['type'=>'file', 'name'=>'image', 'label'=>'Image'])
                        </div>
                    </div>
                </div>
                {{-- data in arabic --}}
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">Data in Arabic</div>
                        <div class="card-body">
                                @input(['name'=>'title_ar', 'label'=>'Title', 'value'=>$service->title_ar])
                                @textarea(['name'=>'description_ar', 'label'=>'Description', 'value'=>$service->description_ar])
                                @textarea(['name'=>'body_ar', 'label'=>'Body', 'value'=>$service->body_ar, 'class'=>'ckeditor'])
                        </div>
                    </div>
                </div>
            </div>

        {{-- buttons --}}
        <div class="card">
                <div class="card-body">@button(['title'=>'Save', 'icon'=>'floppy-o'])</div>
        </div>
@endsection

resources/views/admin/dubai-services/index.blade.php
@extends('admin.layouts.master')
@section('breadcrumb') @breadcrumb([ 'title'=>'Dubai Services', 'crumbs'=>[ ['title'=>'Dubai Services', 'url'=>'']
] ])
@endsection

@section('content')

    {{-- search block --}}
    <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-10">
                        <form class="form-inline" method="GET">
                            <input name="key" type="text" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" placeholder="key.." value="{{request('key', '')}}">
                            <button type="submit" class="btn btn-primary mb-2"><i class="fa fa-search"></i> Search</button>
                        </form>
                    </div>
                    <div class="col-2 text-right">
                        <a href="{{route('admin.dubai-services.create')}}" class="btn btn-default"><i class="fa fa-plus-circle"></i> Add new</a>
                    </div>
                </div>

            </div>
        </div>

    {{-- content block --}}
    <div class="card">
    <div class="card-body">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Image</th>
                    <th scope="col">Title</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($services as $service)
                <tr>
                    <th scope="row">{{$service->id}}</th>
                    <td>@thumb(['image'=>$service->image, 'title'=>$service->title_en])</td>
                    <td>{{$service->title_en}}</td>
                    <td class="text-right">
                        @actionLink(['url'=>route('admin.dubai-services.edit', $service->id), 'icon'=>'fa-pencil-square-o fa-2x', 'tooltip'=>'Edit'])
                        @deleteLink(['url'=>route('admin.dubai-services.destroy', $service->id), 'icon'=>'trash fa-2x', 'tooltip'=>'Delete', 'confirm'=>'Are you sure to delete?'])
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <div class="text-right">
                {{ $services->links() }}
            </div>

    </div>
</div>
@endsection