routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('auth:web')->group(function () {
    Route::view('/', 'admin.dashboard.index')->name('dashboard.index');
    Route::resource('users', 'UsersController');
    Route::resource('home-banners', 'HomeBannersController');
    Route::resource('pages', 'PagesController');
    Route::resource('services', 'ServicesController');
    Route::resource('categories', 'CategoriesController');
    Route::resource('image-uploader', 'ImageUploaderController')->only(['store', 'destroy']);
    Route::resource('offers', 'OffersController');
    Route::resource('events', 'EventsController');
    Route::get('events/{id}/show-in-home', 'EventsController@showInHome')->name('events.show-in-home');
    Route::get('offers/{id}/show-in-home', 'OffersController@showInHome')->name('offers.show-in-home');
    Route::resource('programs', 'ProgramsController');
    Route::get('programs/{id}/show-in-home', 'ProgramsController@showInHome')->name('programs.show-in-home');
    Route::resource('certificates', 'CertificatesController');
    Route::resource('dubai-services', 'DubaiServicesController');
    Route::resource('partners', 'PartnersController');
    Route::resource('newsletters', 'NewslettersController');
    Route::resource('contacts', 'ContactsController');
    Route::resource('hajj-programs', 'HajjProgramsController');
    Route::resource('omra-programs', 'OmraProgramsController');
    Route::resource('hajj-hotels', 'HajjHotelsController');
    Route::resource('omra-hotels', 'OmraHotelsController');
    Route::apiResource('photos', 'PhotosController');
    Route::view('gallery/photos', 'admin.gallery.photos')->name('gallery.photos');
    Route::resource('bookings', 'BookingsController');
    Route::get('settings', 'SettingsController@index')->name('settings.index');
    Route::get('settings/social', 'SettingsController@editSocialMedia')->name('settings.social');
    Route::post('settings/social', 'SettingsController@updateSocialMedia')->name('settings.update-social');
    Route::get('settings/pages-header', 'SettingsController@editPagesHeader')->name('settings.pages-header');
    Route::post('settings/pages-header', 'SettingsController@updatePagesHeader')->name('settings.update-pages-header');
});

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
*/
Route::namespace('Front')->prefix('{lang?}')->group(function () {
    Route::view('/', 'front.home');
    Route::get('pages/{slug}', 'PagesController@show');
    Route::resource('services', 'ServicesController')->only(['index', 'show']);
    Route::resource('dubai-services', 'DubaiServicesController')->only(['index', 'show']);
    Route::resource('offers', 'OffersController')->only(['index', 'show']);
    Route::get('our-programs', 'ProgramsController@categories');
    Route::get('our-programs/{category_slug}/programs', 'ProgramsController@index');
    Route::get('our-programs/{program_slug}', 'ProgramsController@show');
    Route::resource('certificates', 'CertificatesController')->only(['index']);
    Route::get('contact-us', 'ContactsController@show');
    Route::post('contacts/send', 'ContactsController@send');
    Route::get('jobs', 'JobsController@show');
    Route::post('jobs/send', 'JobsController@send');
    Route::resource('hajj-programs', 'HajjProgramsController')->only(['index', 'show']);
    Route::resource('umra-programs', 'OmraProgramsController')->only(['index', 'show']);
    Route::resource('hajj-hotels', 'HajjHotelsController')->only(['index', 'show']);
    Route::resource('umra-hotels', 'OmraHotelsController')->only(['index', 'show']);
    Route::view('gallery/photos', 'front.gallery.photos');
    Route::resource('newsletters', 'NewslettersController')->only(['index', 'show']);

    Route::resource('events', 'EventsController')->only(['index', 'show']);

    Route::middleware('auth:web')->group(function(){
        Route::get('programs/{slug}/book', 'BookingsController@create')->name('bookings.create');
        Route::post('programs/{slug}/book', 'BookingsController@store')->name('bookings.store');
        Route::get('programs/{slug}/book/response', 'BookingsController@response')->name('bookings.response');
    });
});

app/HomeBanner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class HomeBanner extends Model
{
    protected $fillable = ['image', 'alt_en', 'description_en', 'alt_ar', 'description_ar'];

    public $timestamps = false;

    public function getImageAttribute($value){
        if($value){
            return [
                'original'=>asset('storage/home-banners/'.$value),
                'thumb'=>asset('storage/home-banners/thumb/'.$value)
            ];
        }
        return $value;
    }

}

app/Http/Controllers/Admin/HomeBannersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\HomeBanner;
use App\Http\Traits\ImageTrait;

class HomeBannersController extends Controller
{
    use ImageTrait;

    public function index(){
        $banners = HomeBanner::all();
        return view('admin.home-banners.index')->with('banners', $banners);
    }

    public function create(){
        return view('admin.home-banners.create');
    }

    public function store(Request $request){

        $this->validate($request, [
            'image'=>'required|image|max:2000'
        ]);

        $inputs = $request->except(['image']);
        //upload image
        if($request->hasFile('image')){
            if ($request->file('image')->isValid()) {
                $inputs['image'] = $this->uploadImageAndFit($request->image, 'home-banners', 100);
            }
        }

        $banner = HomeBanner::create($inputs);
        flash()->success('data saved successfully');
        return \redirect()->route('admin.home-banners.index');
    }

    public function edit($id){
        $banner = HomeBanner::findOrFail($id);
        return view('admin.home-banners.edit')->with('banner', $banner);
    }

    public function update(Request $request, $id){
        $this->validate($request, [
            'image'=>'nullable|image|max:2000'
        ]);

        $inputs = $request->except(['image']);

        $banner = HomeBanner::findOrFail($id);

        //upload image
        if($request->hasFile('image')){
            $this->deleteImage('home-banners', $banner->getOriginal('image'));
            $inputs['image'] = $this->uploadImageAndFit($request->image, 'home-banners', 100);
        }

        $banner->update($inputs);
        flash()->success('data saved successfully');
        return \redirect()->route('admin.home-banners.index');
    }

    public function destroy($id){
        $banner = HomeBanner::findOrFail($id);
        $this->deleteImage('home-banners', $banner->getOriginal('image'));
        $banner->delete();
        flash()->success('data deleted successfully');
        return redirect()->back();
    }
}

resources/views/admin/home-banners/create.blade.php
@extends('admin.layouts.master')
@section('breadcrumb') @breadcrumb([ 'title'=>'Home banners', 'crumbs'=>[ 
    ['title'=>'Settings', 'url'=>route('admin.settings.index')],
    ['title'=>'Home banners', 'url'=>route('admin.home-banners.index')], ['title'=>'Create', 'url'=>''] ] ])
@endsection

@section('content')
{{-- content block --}}
<form action="{{route('admin.home-banners.store')}}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        {{-- data in english --}}
        <div class="col-6">
            <div class="card">
                <div class="card-header">Data in English</div>
                <div class="card-body">
                    @input(['type'=>'file', 'name'=>'image', 'label'=>'Image'])
                    @input(['name'=>'alt_en', 'label'=>'Alt'])
                    @textarea(['name'=>'description_en', 'label'=>'Description'])
                </div>
            </div>
        </div>
        {{-- data in arabic --}}
        <div class="col-6">
            <div class="card">
                <div class="card-header">Data in Arabic</div>
                <div class="card-body">
                    @input(['name'=>'alt_ar', 'label'=>'Alt'])
                    @textarea(['name'=>'description_ar','label'=>'Description'])
                </div>
            </div>
        </div>
    </div>

    {{-- buttons --}}
    <div class="card">
            <div class="card-body">@button(['title'=>'Save', 'icon'=>'floppy-o'])</div>
    </div>


@endsection

resources/views/admin/home-banners/edit.blade.php
@extends('admin.layouts.master')
@section('breadcrumb') @breadcrumb([ 'title'=>'Home banners', 'crumbs'=>[ 
    ['title'=>'Settings', 'url'=>route('admin.settings.index')],
    ['title'=>'Home banners', 'url'=>route('admin.home-banners.index')],
['title'=>'Edit', 'url'=>''] ] ])
@endsection

@section('content')

    {{-- content block --}}
    <form action="{{route('admin.home-banners.update', $banner->id)}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="row">
            {{-- data in english --}}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">Data in English</div>
                    <div class="card-body">
                        @input(['type'=>'file', 'name'=>'image', 'label'=>'Image'])
                        @input(['name'=>'alt_en', 'label'=>'Alt', 'value'=>$banner->alt_en])
                        @textarea(['name'=>'description_en', 'label'=>'Description', 'value'=>$banner->description_en])
                    </div>
                </div>
            </div>
            {{-- data in arabic --}}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">Data in Arabic</div>
                    <div class="card-body">
                        @input(['name'=>'alt_ar', 'label'=>'Alt', 'value'=>$banner->alt_ar])
                        @textarea(['name'=>'description_ar','label'=>'Description', 'value'=>$banner->description_ar])
                    </div>
                </div>
            </div>
        </div>

        {{-- buttons --}}
        <div class="card">
                <div class="card-body">@button(['title'=>'Save', 'icon'=>'floppy-o'])</div>
        </div>
@endsection

resources/views/admin/home-banners/index.blade.php
@extends('admin.layouts.master')
@section('breadcrumb') @breadcrumb([ 'title'=>'Home Banners', 'crumbs'=>[ 
    ['title'=>'Settings', 'url'=>route('admin.settings.index')],
    ['title'=>'Home banners', 'url'=>'']
] ])
@endsection

@section('content')

    {{-- search block --}}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-10">
                </div>
                <div class="col-2 text-right">
                    <a href="{{route('admin.home-banners.create')}}" class="btn btn-default"><i class="fa fa-plus-circle"></i> Add new</a>
                </div>
            </div>

        </div>
    </div>

    {{-- content block --}}
    <div class="card">
    <div class="card-body">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Banner</th>
                    <th scope="col">Alt</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($banners as $banner)
                <tr>
                    <td>@thumb(['image'=>$banner->image, 'title'=>$banner->alt_en])</td>
                    <td>{{$banner->alt_en}}</td>
                    <td class="text-right">
                        @actionLink(['url'=>route('admin.home-banners.edit', $banner->id), 'icon'=>'fa-pencil-square-o fa-2x', 'tooltip'=>'Edit'])
                        @deleteLink(['url'=>route('admin.home-banners.destroy', $banner->id), 'icon'=>'trash fa-2x', 'tooltip'=>'Delete', 'confirm'=>'Are you sure to delete?'])
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>


    </div>
</div>
@endsection