routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('auth:web')->group(function () {
    Route::view('/', 'admin.dashboard.index')->name('dashboard.index');
    Route::resource('users', 'UsersController');
    Route::resource('home-banners', 'HomeBannersController');
    Route::resource('pages', 'PagesController');
    Route::resource('services', 'ServicesController');
    Route::resource('categories', 'CategoriesController');
    Route::resource('image-uploader', 'ImageUploaderController')->only(['store', 'destroy']);
    Route::resource('offers', 'OffersController');
    Route::resource('events', 'EventsController');
    Route::get('events/{id}/show-in-home', 'EventsController@showInHome')->name('events.show-in-home');
    Route::get('offers/{id}/show-in-home', 'OffersController@showInHome')->name('offers.show-in-home');
    Route::resource('programs', 'ProgramsController');
    Route::get('programs/{id}/show-in-home', 'ProgramsController@showInHome')->name('programs.show-in-home');
    Route::resource('certificates', 'CertificatesController');
    Route::resource('dubai-services', 'DubaiServicesController');
    Route::resource('partners', 'PartnersController');
    Route::resource('newsletters', 'NewslettersController');
    Route::resource('contacts', 'ContactsController');
    Route::resource('hajj-programs', 'HajjProgramsController');
    Route::resource('omra-programs', 'OmraProgramsController');
    Route::resource('hajj-hotels', 'HajjHotelsController');
    Route::resource('omra-hotels', 'OmraHotelsController');
    Route::apiResource('photos', 'PhotosController');
    Route::view('gallery/photos', 'admin.gallery.photos')->name('gallery.photos');
    Route::resource('bookings', 'BookingsController');
    Route::get('settings', 'SettingsController@index')->name('settings.index');
    Route::get('settings/social', 'SettingsController@editSocialMedia')->name('settings.social');
    Route::post('settings/social', 'SettingsController@updateSocialMedia')->name('settings.update-social');
    Route::get('settings/pages-header', 'SettingsController@editPagesHeader')->name('settings.pages-header');
    Route::post('settings/pages-header', 'SettingsController@updatePagesHeader')->name('settings.update-pages-header');
});

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
*/
Route::namespace('Front')->prefix('{lang?}')->group(function () {
    Route::view('/', 'front.home');
    Route::get('pages/{slug}', 'PagesController@show');
    Route::resource('services', 'ServicesController')->only(['index', 'show']);
    Route::resource('dubai-services', 'DubaiServicesController')->only(['index', 'show']);
    Route::resource('offers', 'OffersController')->only(['index', 'show']);
    Route::get('our-programs', 'ProgramsController@categories');
    Route::get('our-programs/{category_slug}/programs', 'ProgramsController@index');
    Route::get('our-programs/{program_slug}', 'ProgramsController@show');
    Route::resource('certificates', 'CertificatesController')->only(['index']);
    Route::get('contact-us', 'ContactsController@show');
    Route::post('contacts/send', 'ContactsController@send');
    Route::get('jobs', 'JobsController@show');
    Route::post('jobs/send', 'JobsController@send');
    Route::resource('hajj-programs', 'HajjProgramsController')->only(['index', 'show']);
    Route::resource('umra-programs', 'OmraProgramsController')->only(['index', 'show']);
    Route::resource('hajj-hotels', 'HajjHotelsController')->only(['index', 'show']);
    Route::resource('umra-hotels', 'OmraHotelsController')->only(['index', 'show']);
    Route::view('gallery/photos', 'front.gallery.photos');
    Route::resource('newsletters', 'NewslettersController')->only(['index', 'show']);

    Route::resource('events', 'EventsController')->only(['index', 'show']);

    Route::middleware('auth:web')->group(function(){
        Route::get('programs/{slug}/book', 'BookingsController@create')->name('bookings.create');
        Route::post('programs/{slug}/book', 'BookingsController@store')->name('bookings.store');
        Route::get('programs/{slug}/book/response', 'BookingsController@response')->name('bookings.response');
    });
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Category extends Model
{
    use Sluggable;

    protected $fillable = ['image', 'title_en', 'title_ar', 'slug'];

    public $timestamps = false;

    public function getImageAttribute($value){
        if($value){
            return [
                'original'=>asset('storage/categories/'.$value),
                'thumb'=>asset('storage/categories/thumb/'.$value)
            ];
        }
        return $value;
    }

     /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title_en'
            ]
        ];
    }

}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;
use App\Http\Traits\ImageTrait;

class CategoriesController extends Controller
{
    use ImageTrait;

    public function index(Request $request){
        $query = Category::query();

        if($request->filled('key')){
            $query->where('title_en', 'like', "%{$request->key}%")
                ->orWhere('title_ar', 'like', "%{$request->key}%" );
        }

        $categories = $query->paginate(config('system.limit_per_page'));
        return view('admin.categories.index')->with('categories', $categories);
    }

    public function create(){
        return view('admin.categories.create');
    }

    public function store(Request $request){

        $this->validate($request, [
            'image'=>'required|image|max:2000',
            'title_en'=>'required',
            'title_ar'=>'required'
        ]);

        $inputs = $request->except(['image']);
        //upload image
        if($request->hasFile('image')){
            if ($request->file('image')->isValid()) {
                $inputs['image'] = $this->uploadImageAndFit($request->image, 'categories', 370);
            }
        }

        $category = Category::create($inputs);
        flash()->success('data saved successfully');
        return \redirect()->route('admin.categories.index');
    }

    public function edit($id){
        $category = Category::findOrFail($id);
        return view('admin.categories.edit')->with('category', $category);
    }

    public function update(Request $request, $id){
        $this->validate($request, [
            'image'=>'nullable|image|max:2000',
            'title_en'=>'required',
            'title_ar'=>'required'
        ]);

        $inputs = $request->except(['image']);

        $category = Category::findOrFail($id);

        //upload image
        if($request->hasFile('image')){
            $this->deleteImage('categories', $category->getOriginal('image'));
            $inputs['image'] = $this->uploadImageAndFit($request->image, 'categories', 370, 201);
        }

        $category->update($inputs);
        flash()->success('data saved successfully');
        return \redirect()->route('admin.categories.index');
    }

    public function destroy($id){
        $category = Category::findOrFail($id);
        $this->deleteImage('categories', $category->getOriginal('image'));
        $category->delete();
        flash()->success('data deleted successfully');
        return redirect()->back();
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')
@section('breadcrumb') @breadcrumb([ 'title'=>'Programs categories', 'crumbs'=>[ ['title'=>'Programs categories', 'url'=>route('admin.categories.index')], ['title'=>'Create', 'url'=>''] ] ])
@endsection

@section('content')
{{-- content block --}}
<form action="{{route('admin.categories.store')}}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        {{-- data in english --}}
        <div class="col-6">
            <div class="card">
                <div class="card-header">Data in English</div>
                <div class="card-body">
                    @input(['name'=>'title_en', 'label'=>'Title'])
                    @input(['type'=>'file', 'name'=>'image', 'label'=>'Image'])
                </div>
            </div>
        </div>
        {{-- data in arabic --}}
        <div class="col-6">
            <div class="card">
                <div class="card-header">Data in Arabic</div>
                <div class="card-body">
                        @input(['name'=>'title_ar', 'label'=>'Title'])
                </div>
            </div>
        </div>
    </div>

    {{-- buttons --}}
    <div class="card">
            <div class="card-body">@button(['title'=>'Save', 'icon'=>'floppy-o'])</div>
    </div>


@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')
@section('breadcrumb') @breadcrumb([ 'title'=>'Programs categories', 'crumbs'=>[ ['title'=>'Programs categories', 'url'=>route('admin.categories.index')],
['title'=>'Edit', 'url'=>''] ] ])
@endsection

@section('content')

    {{-- content block --}}
    <form action="{{route('admin.categories.update', $category->id)}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="row">
                {{-- data in english --}}
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">Data in English</div>
                        <div class="card-body">
                            @input(['name'=>'title_en', 'label'=>'Title', 'value'=>$category->title_en])
                            @input(['type'=>'file', 'name'=>'image', 'label'=>'Image'])
                        </div>
                    </div>
                </div>
                {{-- data in arabic --}}
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">Data in Arabic</div>
                        <div class="card-body">
                                @input(['name'=>'title_ar', 'label'=>'Title', 'value'=>$category->title_ar])
                        </div>
                    </div>
                </div>
            </div>

        {{-- buttons --}}
        <div class="card">
                <div class="card-body">@button(['title'=>'Save', 'icon'=>'floppy-o'])</div>
        </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master')
@section('breadcrumb') @breadcrumb([ 'title'=>'Programs categories', 'crumbs'=>[ ['title'=>'Programs categories', 'url'=>'']
] ])
@endsection

@section('content')

    {{-- search block --}}
    <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-10">
                        <form class="form-inline" method="GET">
                            <input name="key" type="text" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" placeholder="key.." value="{{request('key', '')}}">
                            <button type="submit" class="btn btn-primary mb-2"><i class="fa fa-search"></i> Search</button>
                        </form>
                    </div>
                    <div class="col-2 text-right">
                        <a href="{{route('admin.categories.create')}}" class="btn btn-default"><i class="fa fa-plus-circle"></i> Add new</a>
                    </div>
                </div>

            </div>
        </div>

    {{-- content block --}}
    <div class="card">
    <div class="card-body">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Image</th>
                    <th scope="col">Title</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categories as $category)
                <tr>
                    <th scope="row">{{$category->id}}</th>
                    <td>@thumb(['image'=>$category->image, 'title'=>$category->title_en])</td>
                    <td><a href="{{route('admin.programs.index', ['category_id'=>$category->id])}}">{{$category->title_en}}</a></td>
                    <td class="text-right">
                        @actionLink(['url'=>route('admin.programs.index', ['category_id'=>$category->id]), 'icon'=>'fa-list fa-2x', 'tooltip'=>'Programs list'])
                        @actionLink(['url'=>route('admin.categories.edit', $category->id), 'icon'=>'fa-pencil-square-o fa-2x', 'tooltip'=>'Edit'])
                        @deleteLink(['url'=>route('admin.categories.destroy', $category->id), 'icon'=>'trash fa-2x', 'tooltip'=>'Delete', 'confirm'=>'Are you sure to delete?'])
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <div class="text-right">
                {{ $categories->links() }}
            </div>

    </div>
</div>
@endsection